name:                minithesis
version:             0.1.0.0
github:              "anoctopus/minithesis"
license:             BSD3
author:              "Amanda Walker"
maintainer:          "amanda@amandawalker.io"
copyright:           "2020 Amanda Walker"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/minithesis#readme>

dependencies:
- name: base
  version: ">= 4.7 && < 5"
- bytestring
- relude
- containers
- random >= 1.2
- vector
# - interpolate
- neat-interpolation
- hspec

default-extensions:
  - ApplicativeDo
  - BangPatterns
  - BlockArguments
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - DerivingStrategies
  - EmptyCase
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedStrings
  - PartialTypeSignatures
  - PatternSynonyms
  - PolyKinds
  - QuasiQuotes
  - RankNTypes
  - ScopedTypeVariables
  - StandaloneDeriving
  - Strict
  - StrictData
  - TupleSections
  - TypeApplications
  - TypeOperators

ghc-options:
  - -Wall
  - -Wcompat
  - -Wredundant-constraints
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Widentities
  - -Wpartial-fields
  - -haddock
  - -fwrite-ide-info
  - -hiedir=.hie
  - -fhide-source-paths
  - -freverse-errors
  # - -fplugin=Clippy

library:
  source-dirs: src

executables:
  minithesis-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - minithesis

tests:
  minithesis-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -haddock
    dependencies:
    - minithesis
